service: th-backend
frameworkVersion: '3'

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  environment:
    SEND_MESSAGE_QUEUE_ARN:
      Fn::GetAtt:
        - SendMessageQueue
        - QueueName
    OPENAI_API_KEY: sk-proj-jx7xhhAMe27SKaDGMKr8T3BlbkFJazp4XlPOqap2HHSU3ttH
    DELAY_STATE_FUNCTION:
      Fn::GetAtt:
        - StepFunctionsStateMachine
        - Arn

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "states:StartExecution"
          Resource: { "Fn::GetAtt" : ["StepFunctionsStateMachine","Arn"]  }
        - Effect: "Allow"
          Action:
            - "states:StopExecution"
          Resource: { "Fn::Join" : ["", ["arn:aws:states:*:*:execution:", { "Fn::GetAtt" : ["StepFunctionsStateMachine","Name"]  }, ":*" ] ]  }
          # "arn:aws:states:::execution::*"
        - Effect: "Allow"
          Action:
            - "sqs:sendmessage"
          Resource: { "Fn::GetAtt" : ["SendMessageQueue","Arn"]  }
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - Fn::GetAtt:
              - conversationTable
              - Arn
            - Fn::GetAtt:
              - pageTable
              - Arn

plugins:
  - serverless-go-plugin
  - serverless-domain-manager
  - serverless-certificate-creator
  # - serverless-lift

custom:
  go:
    baseDir: . # folder where go.mod file lives, if set `handler` property should be set relatively to that folder
    binDir: .bin # target folder for binary files
    cgo: 0 # CGO_ENABLED flag
    cmd: GOARCH=arm64 GOOS=linux go build -tags lambda.norpc # compile command
    monorepo: false # if enabled, builds function every directory (useful for monorepo where go.mod is managed by each function
    supportedRuntimes: ["provided.al2"] # the plugin compiles a function only if runtime is declared here (either on function or provider level) 
    buildProvidedRuntimeAsBootstrap: true # if enabled, builds and archive function with only single "bootstrap" binary (useful for runtimes like provided.al2)
  customCertificate:
    certificateName: '*.trendshub.co.in'
    # idempotencyToken: 'abcsomedomainio' //optional
    # hostedZoneNames: 'trendshub.co.in'
    hostedZoneIds: Z080267715NZAAP58PC3U
    # region: eu-west-1 // optional - default is us-east-1 which is required for custom api gateway domains of Type Edge (default)
    enabled: true
    rewriteRecords: false
  customDomain:
    domainName: backend.trendshub.co.in
    basePath: ''
    stage: dev
    certificateName: '*.trendshub.co.in'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2

functions:
  business_api:
    handler: functions/business_apis/main.go
    events:
      - http: POST /business/login
      - http: OPTIONS /business/login
      - http: GET /business/pages
      - http: OPTIONS /business/pages
      - http: GET /business/conversations
      - http: POST /business/conversations
      - http: OPTIONS /business/conversations
  
  message_wh:
    handler: functions/message_webhook/main.go
    events:
      - http: GET /instagram/webhook
      - http: POST /instagram/webhook
      - http: GET /test/sqs

  message_sqs:
    handler: functions/message_sqs/main.go
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SendMessageQueue
              - Arn
package:
  patterns:
    - '!./**'
  individually: true

resources:
  Resources:
    SendMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SendMessageQueue

    conversationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: conversationTable
        AttributeDefinitions:
          - AttributeName: igsid
            AttributeType: S
          - AttributeName: pageId
            AttributeType: S
          - AttributeName: currentPhase
            AttributeType: N
          - AttributeName: isConversationPaused
            AttributeType: BOOL  # Define the new boolean attribute
        KeySchema:
          - AttributeName: igsid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: PagePhaseIndex
            KeySchema:
              - AttributeName: pageId
                KeyType: HASH
              - AttributeName: currentPhase
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: IsConversationPausedIndex  # Define the new index
            KeySchema:
              - AttributeName: isConversationPaused
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    
    pageTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: pageTable
        AttributeDefinitions: 
          - AttributeName: pageId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: pageId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    # Step Functions state machine that delays, then publishes to SNS topic.
    StepFunctionsStateMachine:
      Type: "AWS::StepFunctions::StateMachine"
      Properties:
        StateMachineName: DelayedSQS
        RoleArn: !GetAtt StepFunctionsServiceRole.Arn
        # Replace "SecondsPath" with "TimestampPath" for scheduling
        DefinitionString: |
          {
            "StartAt": "Delay",
            "Comment": "Publish to SNS with delay",
            "States": {
              "Delay": {
                "Type": "Wait",
                "SecondsPath": "$.delay_seconds",
                "Next": "Send message to SQS"
              },
              "Send message to SQS": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sqs:sendMessage",
                "Parameters": {  
                    "QueueUrl.$": "$.topic",
                    "MessageBody.$": "$.message"
                },
                "End":true
              }
            }
          }

    # Allow Step Functions state machine to publish to SNS topic
    StepFunctionsServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        Path: !Join ["", ["/", !Ref "AWS::StackName", "/"]]
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "AllowStepFunctionsServiceToAssumeRole"
              Effect: "Allow"
              Action: 
                - "sts:AssumeRole"
              Principal:
                Service:
                  - !Sub "states.${AWS::Region}.amazonaws.com"
        Policies:
          -   PolicyName: "PublishToSNSTopic"
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: "Allow"
                    Action:
                      - "sqs:sendmessage"
                    Resource: "arn:aws:sqs:*"

  # Outputs:
  #   StepFunctionsStateMachine:
  #     Description: Step Functions State Machine ARN
  #     Value: !Ref StepFunctionsStateMachine
  #   SNSTopic:
  #     Description: SNS Topic ARN
  #     Value: !Ref SNSTopic