package templates

const (
	SubjectInfluencerAppliedToCollab  = "An influencer applied to your collaboration!"
	SubjectApplicationAccepted        = "Your application has been accepted 🎉"
	SubjectApplicationRejected        = "Your application was not accepted"
	SubjectQuotationRevisionRequested = "Brand has requested a revision on your quotation"
	SubjectNewQuotationReceived       = "New quotation received from influencer"
	SubjectStartCollabReminderToBrand = "Start the collaboration now – influencer is waiting!"
	SubjectCollaborationStarted       = "Collaboration started – contract is now live"
	SubjectNudgeToEndContract         = "Influencer nudged to end the contract and rate"
	SubjectContractEndedForInfluencer = "Contract ended – rate the brand to see their rating"
	SubjectContractEndedForBrand      = "Contract ended – thanks for rating the influencer"
	SubjectInfluencerRatedYou         = "New rating received from influencer"
	SubjectBrandInvitedYouToCollab    = "You've been invited to a collaboration!"
	SubjectWelcomeNewInfluencer       = "Welcome to Trendly, Creator!"
	SubjectWelcomeNewBrand            = "Your brand has been created on Trendly 🎉"
	SubjectEmailVerification          = "Verify your email address for Trendly"
	SubjectPasswordReset              = "Reset your Trendly password"
	SubjectPasswordChanged            = "Your Trendly password has been changed"
	SubjectUnreadMessageReminder      = "You have unread messages on Trendly"
	SubjectBrandEmailInvite           = "You have been invited on Trendly"
	SubjectInfluencerInvite           = "You’ve received a new collab idea on Trendly 💡"
	SubjectInfluencerInviteAccepted   = "Your collab invite was accepted! Start chatting now 🎉"
	SubjectInfluencerInviteRejected   = "Your invite wasn’t accepted—but don’t stop creating ✨"
	SubjectCollaborationTakedown      = "Important: Your collaboration has been taken down"
	SubjectPaymentOrderCreated        = "A payment order has been created for your collaboration"
)
