package templates

const (
	SubjectInfluencerAppliedToCollab           = "An influencer applied to your collaboration!"
	SubjectApplicationAccepted                 = "Your application has been accepted 🎉"
	SubjectApplicationRejected                 = "Your application was not accepted"
	SubjectQuotationRevisionRequested          = "Brand has requested a revision on your quotation"
	SubjectNewQuotationReceived                = "New quotation received from influencer"
	SubjectStartCollabReminderToBrand          = "Start the collaboration now – influencer is waiting!"
	SubjectCollaborationStarted                = "Collaboration started – contract is now live"
	SubjectNudgeToEndContract                  = "Influencer nudged to end the contract and rate"
	SubjectContractEndedForInfluencer          = "Contract ended – rate the brand to see their rating"
	SubjectContractEndedForBrand               = "Contract ended – thanks for rating the influencer"
	SubjectInfluencerRatedYou                  = "New rating received from influencer"
	SubjectBrandRatedInfluencer                = "New rating received from brand"
	SubjectBrandInvitedYouToCollab             = "You've been invited to a collaboration!"
	SubjectWelcomeNewInfluencer                = "Welcome to Trendly, Creator!"
	SubjectWelcomeNewBrand                     = "Your brand has been created on Trendly 🎉"
	SubjectEmailVerification                   = "Verify your email address for Trendly"
	SubjectPasswordReset                       = "Reset your Trendly password"
	SubjectPasswordChanged                     = "Your Trendly password has been changed"
	SubjectUnreadMessageReminder               = "You have unread messages on Trendly"
	SubjectBrandEmailInvite                    = "You have been invited on Trendly"
	SubjectInfluencerInvite                    = "You’ve received a new collab idea on Trendly 💡"
	SubjectInfluencerInviteAccepted            = "Your collab invite was accepted! Start chatting now 🎉"
	SubjectInfluencerInviteRejected            = "Your invite wasn’t accepted—but don’t stop creating ✨"
	SubjectCollaborationTakedown               = "Important: Your collaboration has been taken down"
	SubjectPaymentOrderCreated                 = "A payment order has been created for your collaboration"
	SubjectPaymentReceivedContractStartedBrand = "Payment received — your collaboration is live on Trendly"
	SubjectContractFundedStartedInfluencer     = "Your contract is funded — collaboration started 🎉"
	SubjectPaymentFailedBrand                  = "Payment attempt unsuccessful for your collaboration"
	SubjectShipmentMarked                      = "Your package is on its way! 📦"
	SubjectShipmentRequested                   = "📦 Influencer is waiting for shipment"
	SubjectShipmentDelivered                   = "Great news! Your package has been delivered 🏠"
	SubjectShipmentAcknowledgeReminder         = "Reminder: confirm you received the product with a photo – Trendly"
	SubjectShipmentReceivedForBrand            = "Product Received! Influencer is ready to create 📽️"
	SubjectShipmentReceivedForInfluencer       = "Package Received! Time to create some magic ✨"
	SubjectDeliverableRequested                = "Action Required: Brand is waiting for your deliverable 📽️"
	SubjectDeliverableSent                     = "New Deliverable Received! Review the video now 📽️"
	SubjectDeliverableRevisionRequested        = "Revision Requested: Brand has shared feedback for changes 📽️"
	SubjectDeliverableApproved                 = "Excellent news! Your deliverable has been approved 🎉"
	SubjectPostRescheduleRequested             = "Reschedule Requested: Influencer has suggested a change in posting date 🗓️"
	SubjectPostRescheduledByBrand              = "Update: Your posting date has been rescheduled 🗓️"
	SubjectPostMarkedLiveForBrand              = "It's LIVE! 🚀 Content has been posted for your review"
	SubjectPostMarkedLiveForInfluencer         = "Congratulations! 🎉 Your post is live"
	SubjectPayoutTransferInfluencer            = "Your payout has been initiated – Trendly"
	SubjectPayoutTransferBrand                 = "Collaboration complete – influencer payout initiated"
	SubjectPayoutTransferFailedInfluencer      = "Issue with your payout transfer – Trendly"
	SubjectPayoutTransferFailedBrand           = "Influencer payout transfer could not be completed"
	SubjectKYCRouteActivatedInfluencer         = "Your payout setup is approved – Trendly"
	SubjectKYCRouteRejectedInfluencer          = "Update on your payout verification – Trendly"
	SubjectKYCRequiredPrepayBlockedInfluencer  = "Urgent: pre-payment is waiting on your profile verification – Trendly"

	// Dispute subjects
	SubjectDisputeRaised        = "A dispute has been raised on your contract – Trendly"
	SubjectDisputeRaisedSupport = "🚨 New contract dispute requires review"
	SubjectDisputeResolved      = "Your contract dispute has been resolved – Trendly"

	// Cancellation subjects
	SubjectCancellationRequested = "Cancellation requested on your contract – Trendly"
	SubjectCancellationApproved  = "Your contract has been cancelled – Trendly"
	SubjectCancellationRejected  = "Your cancellation request was not approved – Trendly"

	// SLA nudge subjects
	SubjectSLANudgeBrandShip         = "Reminder: Your influencer is waiting for the product 📦"
	SubjectSLANudgeBrandReview       = "Reminder: A deliverable is waiting for your review 📽️"
	SubjectSLANudgeInfluencerReceipt = "Reminder: Please confirm you received the product – Trendly"
	SubjectSLANudgeInfluencerVideo   = "Reminder: Your collaboration is waiting for your video – Trendly"
	SubjectSLANudgeInfluencerPost    = "Reminder: Your scheduled posting date has passed – Trendly"
	SubjectSLAEscalationSupport      = "🚨 SLA Escalation: Contract stuck — action required"
)
